require('dotenv').config();
const express = require('express');
const { dbConnection } = require('./src/infrastructure/database/config');
const app = express();
dbConnection();
app.use(express.json());
app.use(express.static('public'));
app.get('/', (req, res) => res.send('SUPERMERCADO-API-READY'));
app.use('/api/products', require('./src/presentation/routes/productRoutes'));
const port = process.env.PORT || 3000;
app.listen(port, () => console.log(` Servidor corriendo en el puerto ${port}`));